### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by josecastillolema** [FIAP-MBA/20mob-cloud-final-project#1]
<img width="873" alt="Screen Shot 2020-08-24 at 06 24 47" src="https://user-images.githubusercontent.com/7546521/91027497-8ece5080-e5d2-11ea-8cf4-d953fc18be1d.png">

**Comment by cesar1287** [comment]
![issue-cloud-project](https://user-images.githubusercontent.com/8919574/91043845-b204fa00-e5ea-11ea-9808-04dadd264410.png)

Resolvido professor, era problema das keys de acesso que tinham expirado.
